#!/bin/sh
set -e

lb config noauto \
 --apt-indices none \
 --architectures armhf \
 --archive-areas 'main contrib non-free' \
 --binary-filesystem ext4 \
 --binary-images tar \
 --bootstrap-qemu-arch armhf \
 --bootstrap-qemu-static /usr/bin/qemu-arm-static \
 --chroot-filesystem none \
 --compression gzip \
 --distribution sid \
 --iso-volume "Gumstix Sid" \
 --iso-publisher "Gumstix https://www.gumstix.com" \
 --linux-flavours none \
 --linux-packages none \
 --mode debian \
 --swap-file-path /swapfile \
 --system normal

cp -rf customization/* config/
